server:
  port: 9090
  servlet:
    context-path: /flight

spring:
  datasource:
    url: jdbc:h2:mem:flightdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    openInView: false
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  batch:
    job.enabled: false
    initialize-schema: ALWAYS
  servlet.multipart:
    max-file-size: 3MB
    max-request-size: 3MB

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    info.milikic.nikola.flightapi: DEBUG
  file:
    name: flight-api.log

users.admin:
  username: admin
  password: admin